### ISSUE TITLE
Crashlytics are not working properly 

### ISSUE THREAD

**Issue by pawarlalit29** [Ereza/CustomActivityOnCrash#7] opened 2015-07-25 07:56 UTC
Crashlytics are not working properly 
this is my code 

 @Override
    public void onCreate() {

        super.onCreate();

        //This makes the library not launch the error activity when the app crashes while it is in background.
        CustomActivityOnCrash.setLaunchActivityEvenIfInBackground(false);
        //This enables CustomActivityOnCrash
        CustomActivityOnCrash.setShowErrorDetails(true);
        CustomActivityOnCrash.setErrorActivityClass(CustomErrorActivity.class);
        CustomActivityOnCrash.install(this);

        Fabric.with(this, new Crashlytics());
        sInstance = this;
    }

**Comment by Ereza** [comment] 2015-07-25 08:33
Hello, "not working properly" means that issues are not being reported?

I just tested it and with this code, which is the same as yours, issues are being properly reported in the Crashlytics web interface:

```java
@Override
    public void onCreate() {
        super.onCreate();

        CustomActivityOnCrash.setLaunchErrorActivityWhenInBackground(false);
        CustomActivityOnCrash.setShowErrorDetails(true);
        CustomActivityOnCrash.setErrorActivityClass(CustomErrorActivity.class);
        CustomActivityOnCrash.install(this);

        Fabric.with(this, new Crashlytics());
```

Can you provide more info?

**Comment by pawarlalit29** [comment] 2015-07-25 10:35
sorry for issue is not mention clearly .
issue is not reported to crashlytics , 
the code is same, 
yesterday i was tested but no crash report in crashlytics dashboard

**Comment by Ereza** [comment] 2015-07-25 12:25
What device and API level are you testing on?

Can you provide a sample project where I can reproduce the issue?

**Comment by pawarlalit29** [comment] 2015-07-27 12:26
sorry for late reply,
device is samsumg s3 and min api 15 
i was not create any sample project bcoz i directly implement on my real project

**Comment by Ereza** [comment] 2015-07-27 13:03
That's strange... I am now testing on a Galaxy S3 I9300 with Android 4.3 (API 18), and I can't get it to report anything, even with CustomActivityOnCrash completely disabled. The logs are full of:

```
07-27 15:01:18.537  20942-20942/cat.ereza.sample.customactivityoncrash I/Fabric﹕ Initializing Crashlytics 2.3.3.61
07-27 15:01:33.907  20942-21012/cat.ereza.sample.customactivityoncrash I/Fabric﹕ Crashlytics report upload FAILED: 55B62A780267-0001-43FB-43B5A56DF48B.cls
07-27 15:01:36.192  20942-21012/cat.ereza.sample.customactivityoncrash I/Fabric﹕ Crashlytics report upload FAILED: 55B629CA0123-0001-3AB6-43B5A56DF48B.cls
07-27 15:01:38.812  20942-21012/cat.ereza.sample.customactivityoncrash I/Fabric﹕ Crashlytics report upload FAILED: 55B629480174-0001-350A-43B5A56DF48B.cls
07-27 15:01:43.307  20942-21012/cat.ereza.sample.customactivityoncrash I/Fabric﹕ Crashlytics report upload FAILED: 55B62B050210-0001-4B2F-43B5A56DF48B.cls
```

I'll take a further look at it but it appears to be some kind of Crashlytics problem, or maybe connectivity problems...

**Comment by pawarlalit29** [comment] 2015-07-27 14:24
ok.

**Comment by Ereza** [comment] 2015-07-27 14:36
I was having network issues, since I was uploading a large file from another device and maybe the connection timed out too quickly.

Right now reports are correctly sent on my sample app, with and without CustomActivityOnCrash enabled:
```
07-27 16:27:28.410  31664-31723/cat.ereza.sample.customactivityoncrash:error_activity I/Fabric﹕ Crashlytics report upload complete: 55B62A780267-0001-43FB-43B5A56DF48B.cls
07-27 16:29:14.535    32734-430/cat.ereza.sample.customactivityoncrash:error_activity I/Fabric﹕ Crashlytics report upload complete: 55B62BA30073-0001-51CE-43B5A56DF48B.cls
07-27 16:29:46.665    32734-430/cat.ereza.sample.customactivityoncrash:error_activity I/Fabric﹕ Crashlytics report upload complete: 55B629CA0123-0001-3AB6-43B5A56DF48B.cls
```

Check that you have Crashlytics properly configured, and that you don't have any network connection issues. If the problem persists, please provide a sample project that displays the problem. Also, please attach the resulting logcat after a crash.

Keep in mind that with the previous code, Crashlytics is the one that launches CustomActivityOnCrash after it has done all its own work... So if the error activity is displayed, you can be almost sure that Crashlytics has been executed normally.

I am closing this issue since as of now, I don't have any means of reproducing it. If you can provide additional info, please comment!

Thanks!

**Closed by Ereza** 2015-07-27 14:36 UTC
