### ISSUE TITLE
Incompatible Issues

### ISSUE THREAD

**Issue by Stackflood** [Ereza/CustomActivityOnCrash#46] opened 2017-11-22 20:33 UTC
Hi,

I am getting this error after adding your library to my project. Kindly help to resolve this issue.

Error:Execution failed for task ':app:processDebugManifest'.
> Manifest merger failed : Attribute meta-data#android.support.VERSION@value value=(25.3.1) from [com.android.support:appcompat-v7:25.3.1] AndroidManifest.xml:27:9-31
	is also present at [com.android.support:support-v4:26.0.0-alpha1] AndroidManifest.xml:27:9-38 value=(26.0.0-alpha1).
	Suggestion: add 'tools:replace="android:value"' to <meta-data> element at AndroidManifest.xml:25:5-27:34 to override.

**Comment by Ereza** [comment] 2017-11-22 20:36
Hi @Stackflood,

Are you sure the error comes from the CustomActivityOnCrash library? We don't use neither 25.3.1 nor 26.0.0-alpha1 versions of the support library.

**Comment by Stackflood** [comment] 2017-11-22 21:33
Yes, I rechecked. Only after the addition of CustomActivityOnCrash library, the error reappears, otherwise the build is successful.

**Comment by Ereza** [comment] 2017-11-22 21:36
What are the dependencies on your main project? Can you try to reproduce it by changing the sample app dependencies/code?

**Comment by Stackflood** [comment] 2017-11-23 19:02
I tried to run the sample app, but I am getting this error : Error:This Gradle plugin requires Studio 3.0 minimum. I am using Android Studio 2.2.2

**Comment by Ereza** [comment] 2017-11-23 23:22
Either update Android Studio to 3.0 or change the version of the Gradle plugin to the one you use on your project. It shouldn't matter, no changes were made to the build scripts that depend on the latest version.

**Comment by Redman1037** [comment] 2017-11-30 11:17
try adding these lines in app build.gradle 

    configurations.all {
    resolutionStrategy.eachDependency { DependencyResolveDetails details ->
        def requested = details.requested
        if (requested.group == 'com.android.support') {
            if (!requested.name.startsWith("multidex")) {
                details.useVersion '26.1.0'
            }
        }
      }

in place of 26.1.0 use your support library version

**Comment by Ereza** [comment] 2017-11-30 11:26
@Redman1037 This can be a workaround, but do you know if the issue is caused by CustomActivityOnCrash? It doesn't look like it.

**Comment by Redman1037** [comment] 2017-11-30 11:34
@Ereza i am not sure bro today is the first time i am seeing this library , i was just checking if there are any major issues with this library . I just saw this issue and wanted to help the user , i have no idea what is causing this issue.

**Comment by Stackflood** [comment] 2017-12-26 12:14
hi @Redman1037, @Ereza , thanks for the help. I updated Android studio and the gradle to the latest version and the library is now working good in my project. Many thanks.

**Comment by Ereza** [comment] 2017-12-26 19:16
Thanks for letting us know @Stackflood, closing this then.

**Closed by Ereza** 2017-12-26 19:16 UTC
Labels: needs more info
