### ISSUE TITLE
app restart problem

### ISSUE THREAD

**Issue by devzwy** [Ereza/CustomActivityOnCrash#43] opened 2017-09-07 02:07 UTC
Hi,author.Thank you for the library.I ran into a small problem,after use your libs,my app was restart two times,the default error page was displayed for the first time,the second burst also restarted the new default error page ,but the system error box pops up between the first and the second .and log print like this:
App already crashed recently, not starting custom error activity because we could enter a restart loop. Are you sure that your app does not crash directly on init?
Thanks again.

**Comment by Ereza** [comment] 2017-11-13 17:15
Hi @devzwy, sorry for taking a long time to reply. When this happens, it's very likely that your app is crashing on start (maybe in the `Application` class, or the first shown activity, or on a background task started when the app is run. This could also be happening if your app registers for system broadcasts and crashes when one of the broadcasts arrives. In this last case, if you receive those broadcasts very often, the app could enter a restart loop, restarting eternally. The library attempts to detect initial app crashes by setting a time limit and showing the error log you saw ("App already crashed recently, not starting custom error activity because we could enter a restart loop. Are you sure that your app does not crash directly on init?") if the last crash was 3s ago or less. But this does not protect against all restart loops, and that's what seems to be happening with your app.

If you can provide more info of the cause of the crashes, I can try to detect that in some case in order to avoid it.

**Comment by Ereza** [comment] 2017-11-20 10:36
Closing this issue. If you still have problems with the new version 2.2.0, please reopen it.

**Closed by Ereza** 2017-11-20 10:36 UTC
Labels: question
