### ISSUE TITLE
No Logs in google developer console

### ISSUE THREAD

**Issue by developerashish01** [Ereza/CustomActivityOnCrash#58] opened 2018-05-01 12:44 UTC
I have been using this library in my app, after few month i noticed that my app is crashing but i am not getting logs on google play developer console, this library works very well, but i could not detect why and where is my app being crashed?

Thanks

**Comment by vantuan88291** [comment] 2018-07-25 02:54
this lib will not let google play service get crash logs, so you have to create a api from your server to log crash from your app, this library can do that

**Comment by Ereza** [comment] 2020-02-19 19:20
Hmmm, can you provide more info about this?

I have several apps using this library and they all show data for crashes in the Developer Console. Maybe this data is obtained from the Crashlytics/Firebase reports? If you don't have any other crash reporting tool, it might be caused by CustomActivityOnCrash not calling the original `UncaughtExceptionHandler` from the operating system... But this can't be done because you would get the "This app has crashed" dialog instead of the Error Activity (well, actually, you would get both at the same time).

**Comment by Ereza** [comment] 2020-12-30 15:52
Closing due to lack of further information.

**Closed by Ereza** 2020-12-30 15:52 UTC
Labels: needs more info
